services:
  app-service:
    build: .
    depends_on:
      - db
    environment:
      MONGODB_CONNECT_URL: mongodb://db:27017/udstudio
    ports:
      - "5000:5000"
    networks:
      - appnet

  db:
    image: mongo:latest # Or a specific version like mongo:6.0
    # ports:
    #   - "27017:27017" # Map host port 27017 to container port 27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db # Persist data in a named volume
    restart: always # Always restart the container if it stops
    networks:
      - appnet
volumes:
  mongodb_data:
networks:
  appnet:
    driver: bridge
